import LegalLayout from "../legal-layout"
import { ShieldAlert } from "lucide-react"

export default function SafetyDisclaimer() {
    return (
        <LegalLayout title="Safety & Liability Disclaimer" icon={ShieldAlert}>
            <div className="space-y-8 text-slate-600 leading-relaxed">
                <section className="bg-amber-50 border-l-4 border-amber-400 p-6 rounded-r-xl">
                    <h3 className="text-amber-900 font-bold mb-2 flex items-center gap-2">
                        ⚠️ CRITICAL NOTICE
                    </h3>
                    <p className="text-amber-800 font-medium">
                        HazLabel is an automated tool designed to assist in GHS compliance. However, chemical safety documentation is highly critical and errors can have severe consequences. By using this platform, you acknowledge that automated systems can make mistakes and you accept full responsibility for verifying all output.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-bold text-slate-900 mb-4">1. Automated Data Extraction (AI Errors)</h3>
                    <p>
                        HazLabel utilizes advanced Artificial Intelligence (AI) and Machine Learning (ML) models to extract information from Safety Data Sheets (SDS). These outputs are provided as <strong>tool-assisted drafts</strong> intended for professional review. While we strive for 100% accuracy, AI models are inherently prone to "hallucinations" or misinterpretations of complex formatting.
                    </p>
                    <p className="mt-4 font-bold text-slate-900">
                        YOU MUST MANUALLY VERIFY EVERY DRAFT PICTOGRAM, HAZARD STATEMENT, AND SIGNAL WORD GENERATED BY HAZLABEL AGAINST THE ORIGINAL SOURCE SDS.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-bold text-slate-900 mb-4">2. No Guarantee of Compliance</h3>
                    <p>
                        The use of HazLabel does not guarantee that your facility is in full compliance with local, national, or international regulations (including but not limited to OSHA HCS, WHMIS, CLP, or UN GHS). Compliance requirements vary by jurisdiction and are subject to change. HazLabel is a tool to support your compliance efforts, not a replacement for professional regulatory oversight.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-bold text-slate-900 mb-4">3. High-Risk Activities</h3>
                    <p>
                        Our platform is NOT designed for use in environments where failure could lead to death, personal injury, or severe environmental damage without human oversight. Do not rely solely on HazLabel-generated labels for handling extremely hazardous substances without secondary verification by a qualified Safety Officer or industrial hygienist.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-bold text-slate-900 mb-4">4. Limitation of Liability</h3>
                    <p>
                        To the maximum extent permitted by law, HazLabel, its founders, and affiliates shall not be liable for any direct, indirect, incidental, or consequential damages resulting from:
                    </p>
                    <ul className="list-disc pl-6 space-y-2 mt-2">
                        <li>Incorrectly generated chemical labels or pictograms.</li>
                        <li>Failure of the platform to identify a specific hazard.</li>
                        <li>Fines or legal penalties imposed on your organization by regulatory bodies.</li>
                        <li>Personal injury or property damage resulting from chemical exposure or accidents.</li>
                    </ul>
                </section>

                <section>
                    <h3 className="text-xl font-bold text-slate-900 mb-4">5. User Obligation & Reuse</h3>
                    <p>
                        As a professional user of HazLabel, you agree to:
                    </p>
                    <ul className="list-disc pl-6 space-y-2 mt-2">
                        <li>Maintain the original SDS for every chemical in your inventory.</li>
                        <li>Double-check all generated labels before printing and application.</li>
                        <li>Regularly audit your chemical vault for accuracy.</li>
                    </ul>
                    <p className="mt-4">
                        HazLabel is not responsible for errors arising from modified, reused, outdated, or externally altered labels, nor from labels printed, distributed, or applied without appropriate professional review.
                    </p>
                </section>

                <section className="bg-slate-50 p-6 rounded-xl border border-slate-200">
                    <h3 className="text-lg font-bold text-slate-900 mb-4">6. Additional Clarifications</h3>
                    <div className="space-y-4 text-sm">
                        <p>
                            <strong>Tool-Assisted Drafts:</strong> HazLabel provides automated, tool-assisted draft outputs based on the information available in the uploaded Safety Data Sheet (SDS) at the time of processing. Final responsibility for accuracy, applicability, and regulatory compliance rests solely with the user.
                        </p>
                        <p>
                            <strong>Regulatory Changes:</strong> Regulatory requirements (including OSHA, GHS, and international standards) change frequently. HazLabel does not guarantee that outputs remain compliant after generation or across all local, national, or international regulatory frameworks. Compliance at the time of generation does not imply indefinite compliance.
                        </p>
                        <p>
                            <strong>Jurisdictional Limitations:</strong> HazLabel does not guarantee suitability for every specific jurisdiction or local safety requirement. It is the user's responsibility to ensure that labels meet the specific legal requirements of their geographic location.
                        </p>
                    </div>
                </section>

                <div className="pt-8 border-t border-slate-200">
                    <p className="text-sm italic">
                        By using the HazLabel platform, you electronically signify your agreement to this Safety & Liability Disclaimer.
                    </p>
                </div>
            </div>
        </LegalLayout>
    )
}
